---
- hosts: all
  gather_facts: False
  tasks:
  - name: install httpd package.
    yum:
      name=httpd
      state=latest
  - name: service httpd start package
    service:
      name=httpd
      state=started
